### ISSUE TITLE
wxAuiNotebook events only for wxAuiNotebook

### ISSUE THREAD

**Issue by ghost** [nhold/wxWidgets#59]
While going through code, I saw that a lot of events that are of interest for anything in a tab are restricted artificially to wxAuiNotebook. Don't you think we should just let them go, even if the tabs are not in a wxAuiNotebook ? I don't think it would break backward compatibility and it would go fully in the dynamic notebook direction.

Your opinion ?

**Comment by mjmacleod** [comment]
I think if some of these events are of interest to managers that are not wxAuiNotebook then an equivalent wxAuiManager event should be made and sent instead - I don't think normal managers should ever send wxAuiNotebook events - though some of the wxAuiNotebook events in future could just be typedef'ed versions of the equivalent wxAuiManager events (in places where it makes sense)

I do think there are probably more manager events that can/should be sent out, however with wxWidgets "crazy" insistence on absolute backwards compatibility - even in places where it makes absolutely no sense and affects very few people - I am very hesitant to add anything to the API without first applying a lot of thought to it, if we add some event that turns out to be a mistake we are stuck with it for eternity as we will never be allowed to change those events.

I think we should keep this as is for now, and then after the merge, and after giving the new stuff a small amount of time to stabilise, we should carefully look at what features AUI may have in future and discuss things like this. I think we should avoid rushing any more last minute features into this branch before the merge.
